<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-158744063-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-158744063-1');
</script>


title: Geek Fix Reparaciones
baseURL: /
params:
  landing_template: home
  palette: blue
  palettes:
    blue:
      sass:
        accent1: '#4598c8'
        accent2: '#93d7ff'
        accent3: '#b8d5ff'
        accent4: '#a2f7c2'
        accent5: '#6289c3'
        accent6: '#53b678'
    green:
      sass:
        accent1: '#21b2a6'
        accent2: '#00ffcc'
        accent3: '#00f0ff'
        accent4: '#76ddff'
        accent5: '#505393'
        accent6: '#ed4933'
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
